### ISSUE TITLE
Query regarding Causality of Model

### ISSUE THREAD

**Issue by stonelazy** [hit-thusz-RookieCJ/FullSubNet-plus#11]
First of all thank you so much for making your implementation public.  I have a query regarding causality of the model published.   

In the [paper](https://arxiv.org/pdf/2203.12188.pdf) it was proposed that the proposed architecture is real-time and i could even see the Inferencer code dealing with [chunks of audio](https://github.com/hit-thusz-RookieCJ/FullSubNet-plus/blob/master/speech_enhance/fullsubnet/inferencer/inferencer.py#L141-L199). Yet, i came across from [one of the comments](https://github.com/hit-thusz-RookieCJ/FullSubNet-plus/issues/10#issuecomment-1231459379) that the model published in the paper/ implementation available here in Github is non-causal.   
Incase if it's not non-causal, would it be possible to list down the changes that are needed to be done to make it causal ? Thanks.

**Comment by hit-thusz-RookieCJ** [comment]
By 'real-time' in the paper, we mean that the rtf of the model is less than 1.
The non-causality of the model is mainly caused by the avgpooling step in the MulCA module, which uses information from the entire time period.
So, if you want to implement a casual model, try doing a dynamic avg-pooling (averaging only the previous frame and the current frame) to replace the original avgpooling in MulCA?

**Comment by stonelazy** [comment]
Thanks for the lightning reply !  
I didn't realize until now that `real-time` and `causality` imply two different meaning until now.    

! So, if you want to implement a casual model
My doubt was that, if the current model isn't causal then how is it that the denoising on a [chunk of audio](https://github.com/hit-thusz-RookieCJ/FullSubNet-plus/blob/master/speech_enhance/fullsubnet/inferencer/inferencer.py#L141-L199) actually works properly ?

**Comment by stonelazy** [comment]
1.) Agreed with the definitions, my understanding is that a model that is **non-causal will not be able to do** a real-time streaming operation. By real-time streaming operation, i mean inferring a 20ms input.  Can you comment on this ?


>  My model can do the streaming operation of subchunk because within the chunk

2.) So, does this mean FullSubNet-Plus can be used for streaming inference i.e 20ms input (or a relatively small amount of input audio length for real-time inference) ?    
3.) If yes to 2, then what exactly will you not be able to do so when the model is non-causal ?    

Thanks.

**Comment by hit-thusz-RookieCJ** [comment]
20ms is too short, even less than one frame for me here. So this situation is equivalent to degradation in order to stream just one frame at a time, into a form that requires casual?
I have not dealt with this case, maybe you can try it yourself?

**Comment by stonelazy** [comment]
> So this situation is equivalent to degradation in order to stream just one frame at a time, into a form that requires casual?   
Based on my exposure, in a typical real-time/streaming scenario usecases, it is expected that the model serves for a small chunk say from min-20ms to max-100ms input audio length. If anything more than that, then jitter buffer in the client will add empty frames and cause distortion to audio.   

> 20ms is too short, even less than one frame for me here.   

a.) Can you mention what is the min frames/length of audio with which your model should be inferred ?    

b.) Can you pls answer 3rd question in my [prev comment](https://github.com/hit-thusz-RookieCJ/FullSubNet-plus/issues/11#issuecomment-1262989504) `If yes to 2, what is the limitation of a model being non-causal` ?

**Comment by hit-thusz-RookieCJ** [comment]
About a), it is described in my paper.
Regarding b), I have no specific experience in landing. If you are interested, you can explore it yourself
