### ISSUE TITLE
About the license for this models

### ISSUE THREAD

**Issue by PINTO0309** [hit-thusz-RookieCJ/FullSubNet-plus#3]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/254_FullSubNet-plus

Thank you.

**Comment by hit-thusz-RookieCJ** [comment]
Thank you for your reminder. I have added the license to the repository.

**Comment by PINTO0309** [comment]
Thank you!!
