### ISSUE TITLE
关于论文中的因果性

### ISSUE THREAD

**Issue by Boson-Lv** [hit-thusz-RookieCJ/FullSubNet-plus#5]
大佬你好，问个问题，关于因果性，看到代码里边TCNBlock使用的归一化是groupnorm(1, channel)，但是输入norm的数据维度是(B,channel,T)，这样是因果的嘛？这样似乎每个通道里边都包含所有帧的信息。

**Comment by hit-thusz-RookieCJ** [comment]
代码里面有casual的选项，填充后应该就是因果的了

**Comment by Boson-Lv** [comment]
emmmm，大佬我想知道的是   归一化是groupnorm(1, channel)，但是输入norm的数据维度是(B,channel,T)，这样是因果的嘛？这样似乎每个通道里边都包含所有帧（包括未来帧）的信息。
我的关注点不是后边的深度可分离卷积层，后面大佬你使用的确是因果的深度可分离卷积。

**Comment by hit-thusz-RookieCJ** [comment]
我个人的理解是，这里的group norm得channel数和我们的通道数是一样的，相当于laynrom了，而这个norm应该是只在Channel这个维度上Norm，不对T进行norm（我的印象里是这样的，具体你可以细看一下Group norm的源码），所以它应该是因果的

**Comment by hit-thusz-RookieCJ** [comment]
不过我的这个工作在MulCA模块处就不能保证因果了（论文中所说的real-time指的是rtf < 1）

**Comment by Boson-Lv** [comment]
要得要得谢谢大佬的解答

**Comment by Boson-Lv** [comment]
嗯嗯，好哒哈哈哈，星星必给！！！
